// Top-level build file where you can add configuration options common to all sub-projects/modules.

// This uploads the mapping files to sentry, only enabled when the properties file exists
// (on the build server).
project.ext.sentryMappingUploadingEnabled = file('sentry.properties').exists()

buildscript {
    repositories {
        google()          // MUST include this
        mavenCentral()    // jcenter() is deprecated
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1' // stable AGP version
        classpath 'io.sentry:sentry-android-gradle-plugin:3.51.0' // latest stable Sentry plugin
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

