// Top-level build file where you can add configuration options common to all sub-projects/modules.

// This uploads the mapping files to sentry, only enabled when the properties file exists
// (on the build server).
project.ext.sentryMappingUploadingEnabled = file('sentry.properties').exists()

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.3' // upgraded
        classpath 'io.sentry:sentry-android-gradle-plugin:3.37.0' // also upgrade Sentry plugin
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()   // 🔄 replaced jcenter() with mavenCentral()
    }
}
